src/dashboard/urls.py
from django.urls import path
from .views import index, home

app_name = 'dashboard'


urlpatterns = [
    path('', index, name='index'),
    path('home', home, name='home'),
]

src/monetab/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', include('dashboard.urls')),
    path('teacher/', include('teacher.urls')),
    path('user/', include('user.urls')),
    path('rapport/', include('rapport.urls')),
]

src/rapport/urls.py
from django.urls import path
from .views import index

app_name = 'rapport'

urlpatterns = [
    path('', index, name='index'),

]

src/student/urls.py
from django.urls import path
from .views import index, add_student, update, delete

app_name = 'student'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_student, name='add'),
    path('update/<int:id>/', update, name='update'),
    path('delete/<int:id>/', delete, name='delete'),
]

src/teacher/urls.py
from django.urls import path
from .views import index, add_teacher, update, delete

app_name = 'teacher'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_teacher, name='add'),
    path('update/<int:id>/', update, name='update'),
    path('delete/<int:id>/', delete, name='delete'),
]

src/user/urls.py
from django.urls import path
from .views import index, add_user, update

app_name = 'user'

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_user, name='add'),
    path('update/<int:id>/', update, name='update'),
    
]

src/templates/base.html
{% load static %}
{% url 'dashboard:home' as d%}
{% url 'student:index' as e%}
{% url 'teacher:index' as t%}
{% url 'rapport:index' as r%}
{% url 'user:index' as u%}
{% url 'student:add' as et%}
{% url 'teacher:add' as te%}
{% url 'user:update' as ue%}
{% url 'student:update' as st%}
{% url 'teacher:update' as ta%}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block title %}<title>Mon Etab - Utilisateurs</title>{% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'student/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'teacher/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'rapport/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
    
</head>

<body class="bg-gray-100 font-sans antialiased">
    <div class="flex min-h-screen">
        <!-- Sidebar -->
        <aside {% if request.path == d %} 
        class="w-64 bg-gray-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == e %} 
        class="w-64 bg-yellow-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == t %} 
        class="w-64 bg-green-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == u %} 
        class="w-64 bg-red-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == r %} 
        class="w-64 bg-blue-900 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        {% if request.path == et %} 
        class="w-64 bg-yellow-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == te %} 
        class="w-64 bg-green-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == st %} 
        class="w-64 bg-yellow-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == ta %} 
        class="w-64 bg-green-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}
        
        {% if request.path == ue %} 
        class="w-64 bg-red-800 text-white flex flex-col justify-between shadow-lg transition-transform transform -translate-x-full lg:translate-x-0 lg:relative lg:shadow-none lg:w-72 lg:flex-shrink-0"
        {% endif %}>
            <div class="p-6 fade-in">
                <h2 class="text-3xl font-bold text-center mb-8">Mon Etab</h2>
                <nav>
                    <ul>
                        <li class="mb-4">
                            <a href="{% url 'dashboard:home' %}" class=" {% if request.path == d %} text-blue-400 {% endif %} hover:text-gray-300 flex items-center transition-colors">
                                <span class="mr-2 text-yellow-400">🏠</span> Tableau de bord 
                            </a>
                        </li>
                        <li class="mb-4">
                            <a href="{% url 'student:index' %}" class=" {% if request.path == e %} text-blue-400 {% endif %} hover:text-gray-300 flex items-center transition-colors">
                                <span class="mr-2 text-green-400">👥</span> Élèves
                            </a>
                        </li>
                        <li class="mb-4">
                            <a href="{% url 'teacher:index' %}" class=" {% if request.path == t %} text-blue-400 {% endif %}  hover:text-blue-300 flex items-center font-medium transition-colors">
                                <span class="mr-2 text-red-400">👩‍🏫</span> Professeurs
                            </a>
                        </li>
                        <li class="mb-4">
                            <a href="{% url 'user:index' %}" class=" {% if request.path == u %} text-blue-400 {% endif %} hover:text-gray-300 flex items-center transition-colors">
                                <span class="mr-2 text-blue-400">👤</span> Utilisateurs
                            </a>
                        </li>
                        <li class="mb-4">
                            <a href="{% url 'rapport:index' %}" class=" {% if request.path == r %} text-blue-400 {% endif %} hover:text-gray-300 flex items-center transition-colors">
                                <span class="mr-2 text-blue-400">📊</span> Rapport
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="p-6 ">
                <a href="{% url 'dashboard:index' %}" class="text-gray-400 hover:text-white flex items-center justify-center">
                    <span class="mr-2">🔓</span> Déconnexion
                </a>
            </div>
        </aside>
        
        
        {% block content %}
        
        
        {% endblock content %}

    </div>
</body>
</html>

src/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Login Page</title>
  </head>
  <body>
    

    <div class="flex flex-wrap justify-center items-center bg-gradient-to-r from-blue-500 to-purple-600 h-screen">
      <div class="md:w-1/3 w-full bg-white rounded-2xl shadow-lg p-8">
        <div class="flex flex-col items-center my-10">
          <img
            src="{% static 'public/logo.png' %}"
            alt="Mon Etab Logo"
            class="w-24 h-24 mb-4"
          />
          <h1 class="text-4xl font-extrabold text-gray-800">Mon Etab</h1>
        </div>
        <div class="text-center text-lg font-semibold text-gray-700">
          <form method="post" action="{% url 'dashboard:home' %}">
            {% csrf_token %}
            <input
              class="w-full p-3 mt-5 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-blue-400 placeholder-gray-500"
              type="text"
              name="username"
              placeholder="Identifiant"
            />
            <input
              class="w-full p-3 mt-5 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-blue-400 placeholder-gray-500"
              type="password"
              name="password"
              placeholder="Mot de passe"
            />
            <button
              type="submit"
              class="w-full p-3 mt-8 bg-blue-500 text-white font-bold rounded-lg hover:bg-blue-700 shadow-md"
            >
              Connexion
            </button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>